creditCheck/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^eligibility/', include('eligibility.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^rate/',include('rate.urls')),

]

eligibility/urls.py
from django.conf.urls import url
from . import views


app_name = 'eligibility'
urlpatterns = [
    #  /eligibility/
    url(r'^$', views.index, name='index'),
    url(r'^check_eligibility/$',views.check_eligibility,name='check_eligibility'),

]

rate/urls.py
from django.conf.urls import url
from . import views

app_name= 'rate'
urlpatterns=[
    url(r'^check_rate/$',views.check_rate,name='check_rate'),

]

eligibility/models.py
from django.db import models
from datetime import date


class Clients(models.Model):
    employee_id = models.IntegerField(default=99999999)
    employee_name = models.CharField(max_length=100)
    employee_status = models.CharField(max_length=10)
    employee_age = models.IntegerField(default=100)
    employee_ssn = models.CharField(max_length=20)
    employee_date = models.DateField(date.today)
    employee_gender = models.CharField(max_length=10)

    def __str__(self):

        return str(self.employee_id) + " - " + str(self.employee_name)

eligibility/forms.py
from django import forms


class IdForm(forms.Form):
    # take employee id
    employee_id =forms.IntegerField(label="Employee ID" ,min_value=1,max_value=9999999)

eligibility/views.py
from django.shortcuts import render
from django.conf.urls import url
from .models import Clients
from eligibility.forms import IdForm



def check_eligibility(request):
    if request.method =='POST': #if the form has been filled
        form = IdForm(request.POST)

        if form.is_valid(): # Data has gone through all the checks
            try:
                form=IdForm()
                employee_id = request.POST['employee_id']
                client = Clients.objects.get(employee_id=employee_id)
                context = {'client_details': client, 'message': True,'form':form}
            except Clients.DoesNotExist:
                return render(request,'eligibility/check_eligibility.html',{'message':'Clients does not exist','form':form})
            return render(request, 'eligibility/check_eligibility.html', context)#redirect after post
    else:
        form = IdForm()#unbound form
        return render(request,'eligibility/check_eligibility.html',{'form':form,'message':'invalid transaction'})


def index(request):
    form = IdForm()
    return render(request,'eligibility/check_eligibility.html',{'form':form})


# def detail(request,client_id):
#
#     client = Clients.objects.get(employee_id=client_id)
#     context = {'client_details':client}
#     return render(request,'eligibility/check_eligibility.html',context)
#

eligibility/templates/eligibility/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-------- jquery------>
    <script>$(document).ready(function () {
        //jquery methods here
       //$("#jumbotron").show()
       // $("#body").hide()
    });</script>



</head>
<body>
<!-- navigation here---->
<div class="navbar navbar-default">
    <div class="container-fluid">
        <!--logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar"><span class="glyphicon glyphicon-align-justify"></span>
            </button>
            <a class="navbar-brand" href="#">
               Credit Check
            </a>
        </div>
        <!--menu items-->
        <div class="collapse navbar-collapse" id="mainNavBar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'eligibility:check_eligibility' %}">Eligibility</a></li>
                <li><a href="#">Rate</a></li>
            </ul>
        </div>

    </div>
</div>


<div class="row" >

   {% block search %}

   {% endblock %}
</div>

<div class="row" id="jumbotron">
    {% block jumbotron %}

        {% endblock %}
</div>
<div class="row" id="body" >
        {% block body %}

        {% endblock %}
</div>



</body>

eligibility/templates/eligibility/check_eligibility.html
{% extends 'eligibility/base.html' %}
{% block title%}Eligibility{% endblock  %}

{% block search %}
<div class ="col-sm-4 col-sm-offset-4 ">
    <div class="container-fluid">
        <form class="form-inline" action="{% url 'eligibility:check_eligibility' %}" method="post">
            {% csrf_token %}

            {{ form.as_table}}
            <input type="submit" class="btn btn-default" onclick="$('#jumbotron').show() "/>


        </form>
    </div>
</div>
{% endblock %}
{% block jumbotron %}
<div class="col-sm-4 col-sm-offset-4">
    <div class="container-fluid">
        <div class="jumbotron">
           <h3 align="center">{{ message }}</h3>
        </div>
    </div>
</div>
{% endblock %}
{% block body %}


            <div class ="col-sm-6 col-sm-offset-3">
                <div class="container-fluid">
                    <div>
                        <table class=" table table-striped table-bordered table-condensed table-hover">
                        <thead>
                        <tr>
                            <th>Employee ID:</th> <th>{{ client_details.employee_id }}</th>
                        </tr>
                        </thead>
                        <tr>
                            <td>Full name:</td> <td>{{ client_details.employee_name }}</td>
                        </tr>
                        <tr>
                            <td>Age:</td> <td>{{ client_details.employee_age }}</td>
                        </tr>

                        <tr>
                            <td>Assignment Status:</td> <td>{{ client_details.employee_status }}</td>
                        </tr>
                        <tr>
                            <td>Gender:</td> <td>{{ client_details.employee_gender }}</td>
                        </tr>


                        <tr>
                            <td>Hire date:</td> <td>{{ client_details.employee_date }}</td>
                        </tr>

                        <tr>
                            <td>SSN:</td> <td>{{ client_details.employee_ssn }}</td>
                        </tr>

                        </table>
                    </div>
                </div>
            </div>


{% endblock %}

eligibility/templates/eligibility/details.html
{% extends 'eligibility/base.html' %}
{% block search %}
<form class="form-inline" action={#  #} method="post">
  <div class="form-group">

    <input type="search" class="form-control" id="employee_id" name="employ_id" value="{{ client_details.employee_id }}" placeholder="Employee ID">
  </div>

  <button type="submit" class="btn btn-default">Search</button>
</form>

{% endblock %}

{% block body %}

    <div class = "row">
            <div class ="col-md-6 col-md-offset-3">
                <div class="container-fluid">
                    <div>
                        <table class=" table table-bordered">
                        <thead>
                        <tr>
                            <th>Employee ID:</th> <th>{{ client_details.employee_id }}</th>
                        </tr>
                        </thead>
                        <tr>
                            <td>Full name:</td> <td>{{ client_details.employee_name }}</td>
                        </tr>
                        <tr>
                            <td>Age:</td> <td>{{ client_details.employee_age }}</td>
                        </tr>

                        <tr>
                            <td>Assignment Status:</td> <td>{{ client_details.employee_status }}</td>
                        </tr>
                        <tr>
                            <td>Gender:</td> <td>{{ client_details.employee_gender }}</td>
                        </tr>


                        <tr>
                            <td>Hire date:</td> <td>{{ client_details.employee_date }}</td>
                        </tr>

                        <tr>
                            <td>SSN:</td> <td>{{ client_details.employee_ssn }}</td>
                        </tr>

                        </table>
                    </div>
                </div>
            </div>
    </div>

{% endblock %}